#!/bin/zsh

# find the latest conversation file of $2 user on $1 server
f=( log_${~1}/${~2}_*(Non[-1]) )

# if there is any, tail it
if [[ -n $f ]]; then
    f=$f[1]
    print "Last conversation on "${f[-6,-5]}.${f[-8,-7]}.${f[-12,-9]}":"
    tail $f 
    print -- '---'
else
    echo 'No history found.'
fi
