#!/bin/zsh

# f=( log_${~1}/(user_|)${~2}_*(Non[-1]) )
f=( log_${1}/${2}_*(Non[-2,$]) )
if [[ -n $f ]]; then
    if (( $(wc -l < $f[2]) < 5 )); then
        echo -n "Conversation on "
        stat -c '%y' $f[1] | cut -d' ' -f1
        tail $f[1]
    fi
    echo -n "Conversation on "
    stat -c '%y' $f[2] | cut -d' ' -f1
    tail $f[2]
    print -- '---'
else
    echo 'No history found.'
fi
